"""
free_fermion_ea.py
==================
Exact computation of Z2 Entanglement Asymmetry (EA) and related observables
for free-fermion (BdG) models after quantum quench.

Models supported:
  - TFIM:       H = -J sum_i sz_i sz_{i+1} - g sum_i sx_i
  - XY chain:   H = -sum_i [(1+gamma)/4 sx_i sx_{i+1} + (1-gamma)/4 sy_i sy_{i+1}] - h/2 sum_i sz_i

Initial state:
  |psi_theta> = prod_i [cos(theta/2)|up> + sin(theta/2)|down>]  (product state in sz basis)

Observable:
  Z2 EA: DeltaS_A(t) = S(rho_tilde_A) - S(rho_A)
  where rho_tilde_A = (rho_A + Q_A rho_A Q_A) / 2,  Q_A = prod_{j in A} (1 - 2n_j)

Formulas verified against Round-2 agent review (Phase 3):
  - S+/S- includes + log(p+/-) normalization term
  - r(1/2) = 1 - ln2  (l'Hopital corrected)
  - Single-step time evolution (no accumulation drift)
  - det(1-2C_A) via eigenvalue product

Author: Auto-generated by Amplify Phase 4a
"""

import numpy as np
from scipy.linalg import eigh
import warnings

# ── BdG Hamiltonian builders ────────────────────────────────────────────────


def build_TFIM_BdG(N, g, J=1.0, pbc=True):
    """
    Build the TFIM BdG (Nambu) Hamiltonian matrix.
    H_BdG is (2N x 2N), real, antisymmetric in Majorana representation,
    but we work in the complex correlator picture.

    In the Jordan-Wigner fermion basis:
      H = -J sum_i c_i^dag c_{i+1} + h.c. - J sum_i c_i c_{i+1} + h.c. - g sum_i (1 - 2n_i)
    
    Single-particle BdG in (particle, hole) Nambu basis:
      H_BdG = [[A, B], [-B*, -A*]]
    where:
      A_ij = -g delta_ij - J/2 (delta_{i,j+1} + delta_{i,j-1})
      B_ij = -J/2 (delta_{i,j+1} - delta_{i,j-1})
    
    Returns eigenvalues eps_k (>= 0) and transformation matrix V (unitary).
    The positive-energy eigenvalues correspond to Bogoliubov quasiparticles.
    
    For computing correlators, we directly work with the one-body Hamiltonian.
    """
    # Build A (hopping + onsite) and B (pairing) matrices
    A = np.zeros((N, N))
    B = np.zeros((N, N))

    for i in range(N):
        A[i, i] = -g
        j = (i + 1) % N if pbc else i + 1
        if j < N:
            A[i, j] = -J / 2
            A[j, i] = -J / 2
            B[i, j] = -J / 2
            B[j, i] = J / 2

    # Full BdG matrix (2N x 2N)
    HBdG = np.zeros((2 * N, 2 * N))
    HBdG[:N, :N] = A
    HBdG[:N, N:] = B
    HBdG[N:, :N] = -B
    HBdG[N:, N:] = -A

    return HBdG


def build_XY_BdG(N, h, gamma, J=1.0, pbc=True):
    """
    Anisotropic XY chain BdG Hamiltonian.
    H = -sum_i [(1+gamma)/4 sx_i sx_{i+1} + (1-gamma)/4 sy_i sy_{i+1}] - h/2 sum_i sz_i

    After JW mapping:
      A_ij = -h/2 delta_ij - J*(1+gamma)/4 (delta_{i,j+1} + delta_{i,j-1})   [wrong: use below]
    
    Correct JW mapping for XY chain:
      A_ij = -h/2 delta_ij - 1/2 (delta_{i,j+1} + delta_{i,j-1})
      B_ij = gamma/2 (delta_{i,j+1} - delta_{i,j-1})
    (using convention H_XY = -sum [(1+gamma)/4 sx sx + (1-gamma)/4 sy sy] = -sum [1/2(c^dag c_{i+1} + h.c.) + gamma/2(c c_{i+1} + h.c.)])
    """
    A = np.zeros((N, N))
    B = np.zeros((N, N))

    for i in range(N):
        A[i, i] = -h / 2
        j = (i + 1) % N if pbc else i + 1
        if j < N:
            A[i, j] = -0.5
            A[j, i] = -0.5
            B[i, j] = gamma / 2
            B[j, i] = -gamma / 2

    HBdG = np.zeros((2 * N, 2 * N))
    HBdG[:N, :N] = A
    HBdG[:N, N:] = B
    HBdG[N:, :N] = -B
    HBdG[N:, N:] = -A

    return HBdG


# ── BdG solver ───────────────────────────────────────────────────────────────


def solve_BdG(HBdG):
    """
    Diagonalize the BdG Hamiltonian.
    Returns:
      eps: 2N eigenvalues (particle-hole symmetric: sum to zero)
      V: 2N x 2N unitary transformation matrix (columns = eigenvectors)
    
    For correlator evolution: C(t) = V diag(e^{-i eps_k t}) (V^dag C(0) V) diag(e^{i eps_k t}) V^dag
    """
    eps, V = eigh(HBdG)
    return eps, V


# ── Initial state ─────────────────────────────────────────────────────────────


def initial_correlator(N, theta):
    """
    Initial correlator matrix C_ij(0) = <c_i^dag c_j>(0) for product state
    |psi_theta> = prod_i [cos(theta/2)|up> + sin(theta/2)|down>]

    In JW convention: |up> = empty fermion, |down> = occupied.
    So lambda = <n_j> = sin^2(theta/2) for all j.

    Returns N x N complex Hermitian matrix (diagonal).
    """
    lam = np.sin(theta / 2) ** 2
    return lam * np.eye(N, dtype=complex)


def initial_correlator_full_BdG(N, theta):
    """
    Correlator in 2N-dimensional Nambu space for BdG time evolution.
    C_Nambu(0) = [[C(0), 0], [0, I - C(0)^T]] = [[lambda*I, 0], [0, (1-lambda)*I]]
    """
    lam = np.sin(theta / 2) ** 2
    C_full = np.zeros((2 * N, 2 * N), dtype=complex)
    C_full[:N, :N] = lam * np.eye(N)
    C_full[N:, N:] = (1 - lam) * np.eye(N)
    return C_full


# ── Time evolution ────────────────────────────────────────────────────────────


def evolve_correlator(C_full_0, V, eps, t):
    """
    Single-step time evolution of full Nambu correlator.
    C_full(t) = V diag(e^{-i eps_k t}) V^dag C_full(0) V diag(e^{i eps_k t}) V^dag

    NO step-by-step accumulation (prevents orthogonality drift).

    Returns: 2N x 2N complex matrix.
    """
    phase = np.exp(-1j * eps * t)
    # V^dag C(0) V
    VdagC0V = V.conj().T @ C_full_0 @ V
    # Apply phases: diag(e^{-i eps t}) @ VdagC0V @ diag(e^{i eps t})
    C_rot = phase[:, None] * VdagC0V * phase[None, :].conj()
    # Back-transform
    return V @ C_rot @ V.conj().T


def get_subsystem_correlator(C_full, NA):
    """Extract NA x NA physical correlator C_A from full 2N Nambu correlator."""
    return C_full[:NA, :NA]


# ── Entropy and EA computation ────────────────────────────────────────────────


def _binary_entropy(x, eps=1e-15):
    """h(x) = -x log x - (1-x) log(1-x), with 0*log(0) = 0."""
    x = np.clip(x, eps, 1 - eps)
    return -x * np.log(x) - (1 - x) * np.log(1 - x)


def entropy_from_correlator(CA):
    """
    Von Neumann entropy of Gaussian state from correlator C_A.
    S = sum_k h(lambda_k) where lambda_k = eigenvalues of C_A.
    """
    lam = np.linalg.eigvalsh(CA).real
    return np.sum(_binary_entropy(lam))


def parity_expectation(CA):
    """
    <Q_A> = prod_k (1 - 2 lambda_k)  where lambda_k = eig(C_A)
    Use eigenvalue product for numerical stability (NOT det).
    """
    lam = np.linalg.eigvalsh(CA).real
    return np.prod(1 - 2 * lam)


def _r_k(lam, eps=1e-10):
    """
    r_k = [(1-lam) log(1-lam) - lam log(lam)] / (1 - 2*lam)
    At lam = 1/2: l'Hopital gives r(1/2) = 1 - ln(2) (corrected from Phase 3 bug fix).
    """
    denom = 1 - 2 * lam
    near_half = np.abs(denom) < eps
    
    result = np.zeros_like(lam, dtype=float)
    
    # Regular points
    mask = ~near_half
    lam_r = np.clip(lam[mask], eps, 1 - eps)
    num = (1 - lam_r) * np.log(1 - lam_r) - lam_r * np.log(lam_r)
    result[mask] = num / (1 - 2 * lam_r)
    
    # l'Hopital limit at lam = 1/2: r(1/2) = 1 - ln(2)
    result[near_half] = 1.0 - np.log(2.0)
    
    return result


def symmetry_resolved_entropies(CA):
    """
    Compute S+, S- (symmetry-resolved entropies for Z2 parity sectors).
    
    CORRECTED formula (Phase 3 bug fixes applied):
      S_+/- = -[d_n P0 +/- d_n P_pi] / (2 p_+/-) + log(p_+/-)
    where:
      P0 = 1  (at n=1)
      P_pi = <Q_A> = prod(1-2 lam_k)
      d_n P0 |_{n=1} = sum_k a_k  = -S(rho_A)
      d_n P_pi |_{n=1} = P_pi * sum_k r_k
    
    Guard: if p_- -> 0 (near DQPT critical time), set S_- = 0.
    
    Returns: (S_plus, S_minus, p_plus, p_minus)
    """
    lam = np.linalg.eigvalsh(CA).real
    lam = np.clip(lam, 1e-15, 1 - 1e-15)
    
    # Per-mode quantities
    a_k = lam * np.log(lam) + (1 - lam) * np.log(1 - lam)   # entropy weight (<= 0)
    r_k = _r_k(lam)
    
    # Parity expectation
    P_pi = np.prod(1 - 2 * lam)  # <Q_A>
    
    # Partial derivatives at n=1
    dn_P0 = np.sum(a_k)          # = -S(rho_A)
    dn_Ppi = P_pi * np.sum(r_k)
    
    # Sector probabilities
    p_plus = (1 + P_pi) / 2
    p_minus = (1 - P_pi) / 2
    
    # Symmetry-resolved entropies (corrected: includes + log p term)
    if p_plus < 1e-12:
        S_plus = 0.0
    else:
        S_plus = -(dn_P0 + dn_Ppi) / (2 * p_plus) + np.log(p_plus)
    
    if p_minus < 1e-12:
        S_minus = 0.0   # guard: empty sector has zero entropy
    else:
        S_minus = -(dn_P0 - dn_Ppi) / (2 * p_minus) + np.log(p_minus)
    
    return S_plus, S_minus, p_plus, p_minus


def entanglement_asymmetry(CA):
    """
    Z2 Entanglement Asymmetry:
    DeltaS_A = S(rho_tilde_A) - S(rho_A)
    
    where S(rho_tilde_A) = H(p+, p-) + p+ S+ + p- S-
    
    Returns: (DeltaS, S_rho_A, S_tilde, P_pi, p_plus, p_minus)
    """
    S_rho = entropy_from_correlator(CA)
    S_plus, S_minus, p_plus, p_minus = symmetry_resolved_entropies(CA)
    
    # Shannon entropy of sector probabilities
    H_pp = -p_plus * np.log(max(p_plus, 1e-15)) - p_minus * np.log(max(p_minus, 1e-15))
    
    S_tilde = H_pp + p_plus * S_plus + p_minus * S_minus
    DeltaS = S_tilde - S_rho
    
    P_pi = 2 * p_plus - 1  # = <Q_A>
    
    return DeltaS, S_rho, S_tilde, P_pi, p_plus, p_minus


# ── Loschmidt echo ────────────────────────────────────────────────────────────


def loschmidt_echo(HBdG_i, HBdG_f, N, t_array):
    """
    Compute Loschmidt echo rate function g(t) = -(1/N) log |L(t)|
    and the complex phase arg(G(t)) for topological DQPT identification.
    
    L(t) = |<psi_i | e^{-i H_f t} |psi_i>|^2
    
    For quench from ground state |GS_i> to H_f:
    G(t) = prod_k [cos(eps_k^f t) + i sin(eps_k^f t) * h_k]
    where h_k = (u_k^i u_k^f + v_k^i v_k^f) for Bogoliubov transformation mismatch.
    
    For product state initial state |psi_theta>, we use the full BdG approach.
    
    Returns: (g_t, phase_t, L_t) arrays of length len(t_array)
    """
    # Diagonalize initial and final Hamiltonians
    eps_i, V_i = solve_BdG(HBdG_i)
    eps_f, V_f = solve_BdG(HBdG_f)
    
    # Overlap matrix M = V_i^dag V_f (2N x 2N)
    M = V_i.conj().T @ V_f
    
    # G(t) = det(V_i^dag e^{-i H_f t} V_i)
    # = det(M diag(e^{-i eps_f t}) M^dag)
    # This is the Loschmidt amplitude for the initial ground state |GS_i>.
    # For product state |psi_theta>, we use the correlator approach below.
    
    # For the product state, G(t) = <psi_theta| e^{-i H_f t} |psi_theta>
    # = det(I - C_0 + C_0 U_f(t)^dag) for free fermions
    # where C_0 is initial correlator and U_f(t) is free-fermion time evolution.
    # This is the standard formula for free-fermion Loschmidt amplitude.
    
    eps_f_pos = eps_f[N:]   # positive energy eigenvalues
    
    g_arr = np.zeros(len(t_array))
    phase_arr = np.zeros(len(t_array))
    L_arr = np.zeros(len(t_array))
    
    # For ground state quench, use the simpler formula
    # G(t) = prod_k [cos(eps_k^f t) + i sin(eps_k^f t) * (|f_k|^2 - |g_k|^2)]
    # where f_k, g_k are Bogoliubov coefficients for the transformation between i and f
    # For now, return simple placeholder and compute from correlators
    
    return g_arr, phase_arr, L_arr


def loschmidt_from_correlator(C_full_0, V_f, eps_f, N, t_array):
    """
    Loschmidt echo from free-fermion correlator approach.
    
    G(t) = det(I_N - C_A(0) + (V_f diag(e^{i eps_f^+ t}) V_f^dag)[:N,:N] C_A(0))
    
    Actually, the cleanest formula uses:
    G(t) = det(M(t)) where M(t) is derived from initial correlator and time evolution.
    
    Simplified: use the return rate g(t) = -(1/N) log |det(I - C_0 + C_0(t))|
    where C_0(t) = U(t)^dag C_0 U(t) with U = full-body time evolution.
    
    For the product state with C_0 = lambda * I:
    G(t) = prod_k [e^{i eps_k^f t} lambda + (1-lambda)] for upper quasiparticle modes
    
    Returns: (g_t, phase_t, L_t)
    """
    lam_0 = C_full_0[0, 0].real  # initial occupation (uniform for product state)
    
    g_arr = np.zeros(len(t_array))
    phase_arr = np.zeros(len(t_array))
    L_arr = np.zeros(len(t_array))
    
    # Positive-energy eigenvalues only (N modes)
    eps_pos = eps_f[N:]  # positive eigenvalues
    
    for idx, t in enumerate(t_array):
        # G(t) = prod_k [(1-lam_0) + lam_0 * e^{2i eps_k t}] (for BdG structure)
        # This is the formula for product state initial condition
        factors = (1 - lam_0) + lam_0 * np.exp(2j * eps_pos * t)
        G_t = np.prod(factors)
        L_t = np.abs(G_t) ** 2
        L_arr[idx] = L_t
        if L_t > 1e-300:
            g_arr[idx] = -np.log(L_t) / N
        else:
            g_arr[idx] = np.inf
        phase_arr[idx] = np.angle(G_t)
    
    return g_arr, phase_arr, L_arr


# ── Main computation function ─────────────────────────────────────────────────


def compute_EA_dynamics(model, params_i, params_f, theta, N, NA,
                         t_max=None, dt_early=0.02, dt_late=0.05,
                         t_crossover=20.0):
    """
    Compute time-dependent Z2 EA for a quantum quench.
    
    Parameters
    ----------
    model : 'TFIM' or 'XY'
    params_i : dict with model parameters for initial Hamiltonian
    params_f : dict with model parameters for final Hamiltonian
    theta : float, initial state angle
    N : int, chain length
    NA : int, subsystem size
    t_max : float or None. If None, uses N-dependent formula.
    dt_early, dt_late : time steps for early/late times
    t_crossover : time at which to switch from dt_early to dt_late
    
    Returns
    -------
    dict with keys:
      t_arr, DeltaS_arr, S_rho_arr, P_pi_arr,
      p_plus_arr, p_minus_arr, g_Loschmidt, phase_Loschmidt, L_arr
    """
    # N-dependent t_max
    if t_max is None:
        t_max = max(60.0, 3 * NA / 4.0)
    
    # Build Hamiltonians
    if model == 'TFIM':
        HBdG_i = build_TFIM_BdG(N, params_i['g'])
        HBdG_f = build_TFIM_BdG(N, params_f['g'])
    elif model == 'XY':
        HBdG_i = build_XY_BdG(N, params_i['h'], params_i['gamma'])
        HBdG_f = build_XY_BdG(N, params_f['h'], params_f['gamma'])
    else:
        raise ValueError(f"Unknown model: {model}")
    
    # Diagonalize final Hamiltonian
    eps_f, V_f = solve_BdG(HBdG_f)
    
    # Initial correlator (full Nambu space)
    C_full_0 = initial_correlator_full_BdG(N, theta)
    
    # Time array (two-step resolution)
    t1 = np.arange(0, min(t_crossover, t_max) + dt_early, dt_early)
    if t_max > t_crossover:
        t2 = np.arange(t_crossover + dt_late, t_max + dt_late, dt_late)
        t_arr = np.concatenate([t1, t2])
    else:
        t_arr = t1
    t_arr = np.unique(t_arr[t_arr <= t_max + 1e-10])
    
    NT = len(t_arr)
    DeltaS_arr = np.zeros(NT)
    S_rho_arr = np.zeros(NT)
    P_pi_arr = np.zeros(NT)
    p_plus_arr = np.zeros(NT)
    p_minus_arr = np.zeros(NT)
    
    # Compute for each time point (single-step evolution)
    for idx, t in enumerate(t_arr):
        C_full_t = evolve_correlator(C_full_0, V_f, eps_f, t)
        CA = get_subsystem_correlator(C_full_t, NA).real  # real part (Gaussian state)
        
        DeltaS, S_rho, S_tilde, P_pi, p_plus, p_minus = entanglement_asymmetry(CA)
        DeltaS_arr[idx] = DeltaS
        S_rho_arr[idx] = S_rho
        P_pi_arr[idx] = P_pi
        p_plus_arr[idx] = p_plus
        p_minus_arr[idx] = p_minus
    
    # Loschmidt echo
    g_L, phase_L, L_arr = loschmidt_from_correlator(C_full_0, V_f, eps_f, N, t_arr)
    
    return {
        't': t_arr,
        'DeltaS': DeltaS_arr,
        'S_rho': S_rho_arr,
        'P_pi': P_pi_arr,
        'p_plus': p_plus_arr,
        'p_minus': p_minus_arr,
        'g_Loschmidt': g_L,
        'phase_Loschmidt': phase_L,
        'L': L_arr,
    }


def find_mpemba_crossing_time(t_arr, DeltaS1, DeltaS2, threshold_rel=0.01):
    """
    Find crossing time t_M where DeltaS1 first falls below DeltaS2.
    Assumes DeltaS1(0) > DeltaS2(0) (theta1 more asymmetric initially).
    
    Returns:
      t_M : float (crossing time, or inf if no crossing)
      crossed : bool
    """
    diff = DeltaS1 - DeltaS2
    initial_gap = abs(diff[0])
    
    if initial_gap < 0.05:
        return np.inf, False  # pairs too close, excluded
    
    # Find first negative diff exceeding 1% of initial gap
    threshold = -threshold_rel * initial_gap
    idx = np.where(diff < threshold)[0]
    
    if len(idx) == 0:
        return np.inf, False
    
    # Linearly interpolate for more precise t_M
    i = idx[0]
    if i > 0:
        t_M = t_arr[i - 1] + (t_arr[i] - t_arr[i - 1]) * (-diff[i - 1]) / (diff[i] - diff[i - 1])
    else:
        t_M = t_arr[i]
    
    return t_M, True


# ── Validation benchmarks ─────────────────────────────────────────────────────


def benchmark_initial_EA(N, NA, theta, verbose=True):
    """
    Benchmark 1: Verify DeltaS_A(t=0) against closed-form formula.
    For uniform initial state: all lambda_k = sin^2(theta/2)
    
    Closed form:
      <Q_A> = cos^NA(theta)
      p+/- = (1 +/- cos^NA(theta)) / 2
      S(rho_A) = NA * h(sin^2(theta/2))
      S_+/- from S+/-_formula (see below)
    """
    lam = np.sin(theta / 2) ** 2
    CA = lam * np.eye(NA)
    
    # Numerical result
    DeltaS_num, S_rho_num, _, P_pi_num, p_plus_num, p_minus_num = entanglement_asymmetry(CA)
    
    # Analytical
    P_pi_ana = (1 - 2 * lam) ** NA
    p_plus_ana = (1 + P_pi_ana) / 2
    p_minus_ana = (1 - P_pi_ana) / 2
    S_rho_ana = NA * _binary_entropy(np.array([lam]))[0]
    
    # Symmetry-resolved entropies analytically (using uniform lambda)
    a_k = lam * np.log(lam) + (1 - lam) * np.log(1 - lam)
    if abs(lam - 0.5) < 1e-10:
        r_val = 1.0 - np.log(2.0)
    else:
        r_val = ((1 - lam) * np.log(1 - lam) - lam * np.log(lam)) / (1 - 2 * lam)
    
    dn_P0_ana = NA * a_k
    dn_Ppi_ana = P_pi_ana * NA * r_val
    
    if p_plus_ana > 1e-12:
        S_plus_ana = -(dn_P0_ana + dn_Ppi_ana) / (2 * p_plus_ana) + np.log(p_plus_ana)
    else:
        S_plus_ana = 0.0
    if p_minus_ana > 1e-12:
        S_minus_ana = -(dn_P0_ana - dn_Ppi_ana) / (2 * p_minus_ana) + np.log(p_minus_ana)
    else:
        S_minus_ana = 0.0
    
    H_pp_ana = (-p_plus_ana * np.log(max(p_plus_ana, 1e-15))
                - p_minus_ana * np.log(max(p_minus_ana, 1e-15)))
    S_tilde_ana = H_pp_ana + p_plus_ana * S_plus_ana + p_minus_ana * S_minus_ana
    DeltaS_ana = S_tilde_ana - S_rho_ana
    
    passed = abs(DeltaS_num - DeltaS_ana) < 1e-8
    if verbose:
        print(f"  Benchmark 1 (t=0 EA): theta={theta:.3f}, NA={NA}")
        print(f"    Numerical:   DeltaS={DeltaS_num:.8f}, P_pi={P_pi_num:.8f}")
        print(f"    Analytical:  DeltaS={DeltaS_ana:.8f}, P_pi={P_pi_ana:.8f}")
        print(f"    PASSED: {passed}")
    return passed


def benchmark_symmetric_state(N, NA, verbose=True):
    """
    Benchmark 2: DeltaS_A = 0 for theta=0 (Z2-symmetric initial state).
    At theta=0: lambda=0, all modes empty, <Q_A>=1, ΔS_A=0.
    Tolerance 1e-6 (floating-point entropy near zero).
    """
    CA = np.zeros((NA, NA))
    DeltaS, _, _, P_pi, p_plus, p_minus = entanglement_asymmetry(CA)
    passed = abs(DeltaS) < 1e-6 and abs(P_pi - 1.0) < 1e-10
    if verbose:
        print(f"  Benchmark 2 (theta=0): DeltaS={DeltaS:.2e}, P_pi={P_pi:.8f}, PASSED={passed}")
    return passed


def benchmark_equipartition(N, NA, verbose=True):
    """
    Benchmark 3: At theta=pi/2 (lambda=1/2), P_pi=0, p+=p-=1/2,
    and S+/- = S(rho_A) - ln2 (equipartition).
    """
    theta = np.pi / 2
    lam = 0.5
    CA = lam * np.eye(NA)
    
    S_plus, S_minus, p_plus, p_minus = symmetry_resolved_entropies(CA)
    S_rho = entropy_from_correlator(CA)
    
    # Expected
    S_plus_expected = S_rho - np.log(2.0)
    S_minus_expected = S_rho - np.log(2.0)
    
    passed = (abs(p_plus - 0.5) < 1e-10 and
              abs(p_minus - 0.5) < 1e-10 and
              abs(S_plus - S_plus_expected) < 1e-8 and
              abs(S_minus - S_minus_expected) < 1e-8)
    if verbose:
        print(f"  Benchmark 3 (equipartition): p+={p_plus:.6f}, p-={p_minus:.6f}")
        print(f"    S+={S_plus:.6f}, S-={S_minus:.6f}, S_rho-ln2={S_rho-np.log(2):.6f}")
        print(f"    PASSED: {passed}")
    return passed


def benchmark_CFT_entropy(N, NA, verbose=True):
    """
    Benchmark 4: S(rho_A) at g=1 (TFIM critical) ~ (1/6) log NA + const.
    Check central charge c=1/2 for critical TFIM.
    """
    HBdG = build_TFIM_BdG(N, g=1.0)
    eps, V = solve_BdG(HBdG)
    
    # Ground state correlator: C_ij = <GS|c_i^dag c_j|GS> = (V_hole_pos) @ (V_hole_pos)^dag
    # where V_hole_pos = lower N rows of POSITIVE-energy eigenvectors (hole components)
    # This is correct from the Bogoliubov transformation: c_i = sum_{k>0}(U_{ki} gamma_k + V_{ki}* gamma_k^dag)
    # and C_ij = sum_{k>0} V_{ki} V_{kj}* = (V_hole_pos @ V_hole_pos^dag)_ij
    pos_idx = np.where(eps > 0)[0]
    V_hole_pos = V[N:, pos_idx]  # lower N rows, positive-energy eigenvectors
    C_GS = V_hole_pos @ V_hole_pos.conj().T
    
    NA_arr = np.array([NA // 4, NA // 2, NA])
    S_arr = []
    for na in NA_arr:
        CA = C_GS[:na, :na].real
        S_arr.append(entropy_from_correlator(CA))
    
    # Fit S ~ (c/3) log NA + const (CFT formula for periodic BC, subsystem = L)
    log_NA = np.log(NA_arr)
    # Simple linear regression
    p = np.polyfit(log_NA, S_arr, 1)
    c_measured = p[0] * 3  # slope = c/3
    
    passed = abs(c_measured - 0.5) < 0.05  # within 10% of c=1/2
    if verbose:
        print(f"  Benchmark 4 (CFT at g=1): c_measured={c_measured:.4f}, c_expected=0.5")
        print(f"    S at NA={NA_arr}: {[f'{s:.4f}' for s in S_arr]}")
        print(f"    PASSED: {passed}")
    return passed


def run_all_benchmarks(N=200, NA=20):
    """Run all validation benchmarks. Return True if all pass."""
    print("=" * 50)
    print("Running validation benchmarks")
    print("=" * 50)
    results = []
    results.append(benchmark_initial_EA(N, NA, theta=np.pi / 4))
    results.append(benchmark_initial_EA(N, NA, theta=np.pi / 3))
    results.append(benchmark_initial_EA(N, NA, theta=2 * np.pi / 3))
    results.append(benchmark_symmetric_state(N, NA))
    results.append(benchmark_equipartition(N, NA))
    results.append(benchmark_CFT_entropy(N, NA))
    print("=" * 50)
    print(f"All benchmarks passed: {all(results)} ({sum(results)}/{len(results)})")
    return all(results)
